version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
  build:
    commands:
      - dotnet restore
      - dotnet build
  post_build:
    commands:
      - dotnet publish -c Release -o ./publish

artifacts:
  files:
    - '**/*'
  base-directory: 'publish'
