name: Build and Deploy to AWS

on:
  push:
    branches:
      - qa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish --no-build

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region us-east-1

    - name: Upload to S3
      run: aws s3 cp ./publish s3://${{ secrets.AWS_S3_BUCKET }}/${{ github.sha }}myapp.zip --recursive --exclude "*" --include "*.dll" --include "*.json" --include "*.exe" --include "*.pdb" --include "*.config"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: devbackend # Your Elastic Beanstalk application name
        environment_name: publish-env # Your Elastic Beanstalk environment name
        version_label: ${{ github.sha }}
        region: us-east-1 # Change this to your region
        s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
        s3_key: '${{ github.sha }}myapp.zip' # The key of the zip file in the S3 bucket
