name: Build and Deploy to AWS

on:
  push:
    branches:
      - qa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish --no-build

    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }} # Name of the S3 bucket
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1' # Change this to your region
        SOURCE_DIR: './publish' # This is the directory created by 'dotnet publish'

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: my-application-name # Your Elastic Beanstalk application name
        environment_name: my-environment-name # Your Elastic Beanstalk environment name
        version_label: ${{ github.sha }}
        region: us-east-1 # Change this to your region
        s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
        s3_key: 'myapp.zip' # The key of the zip file in the S3 bucket
